### ISSUE TITLE
Permission to use apollo logo in backstage plugin?

### ISSUE THREAD

**Issue by unredundant** [apollographql/embeddable-explorer#151]
Hey! I recently made a plugin for [Backstage](https://backstage.io/) that allows users to embed apollo graphs in their developer portal.  I also opened this PR https://github.com/backstage/backstage/pull/12766 to showcase the plugin on the Backstage [plugin marketplace](https://backstage.io/plugins) but wanted to make sure it would be ok to use the Apollo logo (Same one you guys have as the icon for this GitHub org).  

If not we can always just use a generic GraphQL logo :)

**Comment by cheapsteak** [comment]
Hi there, 

Sorry this took a while, I think you're good to go! 

The guidelines we received were:

> Essentially, the folks requesting use of our logo can do so as long as:
>1) It's just to describe Apollo service or product
>2) It's non-commercial (e.g., they aren't making money from this)
>3) It's not confusing - the folks aren't using to suggest we are affiliated or endorsing them
>4) It's not in connection with any derivative software

<details>
<summary>
Full doc here
</summary>

Apollo Name and Logo Usage. This is a temporary policy that is subject to review and change by Apollo Graph, Inc. (“Apollo”).

Apollo Name for Usage:
Apollo GraphQL

Apollo Logo for Usage:
[Insert here]

1) When may I use the Apollo logo?

Fair use: To truthfully identify Apollo and our products and services

Trademark law (pursuant to the “nominative fair use” doctrine) allows you to make non-trademark use of Apollo’s name and logo to truthfully refer to or identify Apollo and its products and services. 

Your intended use may be a nominative fair use if you do not suggest that Apollo has endorsed or sponsored your use.

Personal, Non-Commercial Uses: You may use Apollo’s name and logo as long as:
(a) your use is non-commercial in nature (e.g., you are not selling any products with the Apollo name/logo); and 
(b) your use is not misleading and not likely to cause confusion as to whether Apollo sponsored, endorsed, or was otherwise involved in creating or offering your products; 

2) When may I NOT use Apollo’s name and logo?

Uses that are Confusing, False, or Misleading: You may not use our name and logo in a manner that is false or misleading, or in a manner likely to confuse consumers or the public about the source or origin of your products or services. Confusing uses include uses that may cause people to think your products or services are Apollo’s products or services.

3) Uses of Apollo name and logo in connection with derivative software

No branding of derivative software with Apollo name and logo. From a trademark perspective, software that you have modified is different from the software that originates from Apollo, and you may not brand any derivative software with Apollo name and logo, even if you make only minor changes to it, except as provided below (repackaging). 

4) Based on the above, I can use Apollo’s name and logo, what other restrictions exist?

Use the exact name or logo. Apollo’s trademarks should be used in their exact, most up-to-date form. They should neither be abbreviated nor combined with other words.

“Mark” the Name or Logo. The first or most prominent use of Apollo’s name or logo should be accompanied by a “tm” symbol (“™”), to indicate that it is a trademark; you may also use the “r in a circle” symbol (“®”), if the trademark in question is a registered trademark. If you aren’t sure, using the “tm” symbol (“™”) is fine. 

Credit the Name or Logo. The following notice text should appear somewhere nearby your first or most prominent mention of Apollo’s name or logo (for example in a footer). If that’s not practical, you may include it in a reasonable alternate location:

        [mark] is a trademark of Apollo Graph, Inc.

Any goodwill generated by use of the Apollo name and logo shall inure solely to the benefit of Apollo.

How Do I Report Trademark Abuse?
Please report any misuse of Apollo’s name and logo to legal@apollographql.com, and provide us with as much information as you can about the use you think might be infringing. We’ll investigate the use, and take appropriate action, if warranted.



</details>

**Comment by unredundant** [comment]
Wooo all good, ty for getting back to me!
